client/urls.py
from django.urls import path
from .views import ClientRegistration, ClientLogin, client_logout, ClientProfile

app_name = 'client'
urlpatterns = [
    path('registration/', ClientRegistration.as_view(), name='registration'),
    path('login/', ClientLogin.as_view(), name='login'),
    path('logout/', client_logout, name='logout'),
    path('profile/', ClientProfile.as_view(), name='profile')
]

gag/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('client/', include('client.urls'))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import MainIndex, UploadPost, PostLike

app_name = 'main'
urlpatterns = [
    path('', MainIndex.as_view(), name='index'),
    path('upload/', UploadPost.as_view(), name='upload'),
    path('cat/<int:id>/', MainIndex.as_view(), name='cat'),
    path('post/<str:action>/<int:post_id>/', PostLike.as_view(), name='like')
]

templates/layouts/banner.html
{% extends 'layouts/base.html' %}
{% load static i18n %}
{% load bootstrap_pagination %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-2">
                <h6 class="text-secondary font-weight-bold mt-2">KATEGORIYALAR</h6>
                {% for category in categories %}
                    <div class="m-p">
                        <a href="{% url 'main:cat' category.id %}" class="btn m-p text-secondary">
                            <img src="{{ MEDIA_URL }}{{ category.image.url }}" class="cat-img m-p" alt="">
                            <small>{% trans category.name %}</small>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="col-10">
                <img class="img-fluid" src="{% static 'img/banner.gif' %}" alt="">
                <div class="row">
                    <div class="col-9">
                        {% block banner_content %}{% endblock %}
                    </div>
                    <div class="col-3">
                        <img class="img-fluid mt-3" src="{% static 'img/small-banner.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/layouts/base.html
{% load static %}
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
{% trans 'Profil' as profil %}
{% load helpers %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GAG</title>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<nav class="navbar navbar-light border d-flex">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">GAG</a>
        {% if user.is_authenticated %}
            <div class="nav-item dropdown ml-auto">
                <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                    <img class="rounded-circle cover user-avatar" src="{{ user.avatar }}" alt="">
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'client:profile' %}">{{ profil }}</a>
                    <a class="dropdown-item" href="{% url 'client:logout' %}">{% trans 'Chiqish' %}</a>
                </div>
            </div>
            <a href="{% url 'main:upload' %}" class="btn btn-primary rounded-pill"><i
                    class="bi bi-upload"></i>{% trans 'Yuklash' %}</a>
        {% else %}
            <a href="{% url 'client:login' %}" class="btn text-secondary ml-auto mr-3">{% trans "Tizimga kirish" %}</a>
            <a href="{% url 'client:registration' %}"
               class="btn btn-primary rounded-pill">{% trans "Ro'yxatdan o'tish" %}</a>
        {% endif %}
        <div class="nav-item dropdown">
            <a class="nav-link lang_link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                {% for row in LANGUAGES %}
                    {% if row.0 == LANGUAGE_CODE %}
                        {{ row.1|slice:"3" }}
                    {% endif %}
                {% endfor %}
            </a>
            <div class="dropdown-menu">
                {% for row in LANGUAGES %}
                    <a class="btn" href="{{ request.get_full_path|konvert:row.0 }}">{{ row.1 }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</nav>
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="{{ message.tags }} alert alert-dismissible fade show"> <!---->
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}{% endblock %}

<script src="{% static 'vendor/jquery-3.5.1.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/layouts/form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

<div class="container">
    {% block content %}
        <div class="row">
            <div class="col-6 offset-lg-3">
                <div class="card">
                    <div class="card-header">{{ request.title }}</div>
                    <form action="" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form | crispy }}
                        </div>
                        <div class="card-header d-flex border">
                            <button type="submit" class="btn btn-primary ml-auto">{{ request.button_title|default:request.title|default:"Saqlash" }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}
</div>